name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  # continuous-integration:
  #   runs-on: ubuntu-latest
  #   steps:      # Step 1
  #     - uses: actions/checkout@v2
  #     # Step 2
  #     - name: 🔎 Check IP
  #       run: curl https://api.ipify.org
  #     - name: Install requirements for setup
  #       run: pip install -r setup/requirements.txt 
  #     - name: Build and run all dockers
  #       run: make app
  Deploy:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:  
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key.pem 




# chmod 400 private_key.pem
# ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '

#   #Now we have got the access of EC2 and we will start the deploy .
#   cd /home/ubuntu/app/image_cls_app_with_mongo_postgress_minio_mlflow &&
#   git checkout main &&
#   git fetch --all &&
#   git reset --hard origin/main &&
#   git pull origin main &&
#   make app

# '